### ISSUE TITLE
First draft of problem statement

### ISSUE THREAD

**Issue by Marcus1211** [Marcus1211/741_project#2]
Please review the first draft of problem statement
https://github.com/Marcus1211/741_project/tree/main/docs/ProblemStatementAndGoals

Name: Runze Zhao
email: zhaorz@mcmaster.ca
github ID: Marcus1211
Supervisor: Dr. Emil Sekerinski
Project Name: Real Estate Indicator
Project Topic: Real Estate market analysis and prediction
Traditional
github repo url https://github.com/Marcus1211/741_project
branch: main

**Comment by smiths** [comment]
@Marcus1211 I don't have enough information in the problem statement to judge the suitability of the project in terms of the domain and in terms of difficulty.  Are there any on-line resources you can point to that do similar calculations, or maybe there is a paper or web article that shows the relevant equations?  If those resources don't exist, can you let me know what equations you'll be working with?  How is the prediction made?  What do you mean by evaluation of the stability of the current market?  Is there some kind of stability metric that you will be calculating?  Evaluation isn't really an output, but rather what people do with the outputs.

**Comment by Marcus1211** [comment]
I've updated the scope of the problem and project. The focus now would be using regression model techniques in machine learning to give predictions. Please review.
The paper reference can be found here https://ieeexplore.ieee.org/abstract/document/8882834/references#references
